services:
  pgsql:
    image: oroinc/pgsql:17.4-alpine
    ports: ['5432']
    labels:
      com.symfony.server.service-prefix: ORO_DB
    environment:
      POSTGRES_USER: oro_db_user
      POSTGRES_DB: oro_db
      POSTGRES_PASSWORD: oro_db_pass
      POSTGRES_ROOT_PASSWORD: oro_db_pass
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U$${POSTGRES_USER} -d$${POSTGRES_DB}"
      interval: 5s
      timeout: 30s
      start_period: 40s
    restart: on-failure
  redis:
    image: redis:7.4.2-alpine
    ports: ["6379"]
    labels:
      com.symfony.server.service-prefix: ORO_REDIS
  mailcatcher:
    image: schickling/mailcatcher
    ports: ['1025', '1080']
    labels:
      com.symfony.server.service-prefix: ORO_MAILER
  gotenberg:
    image: gotenberg/gotenberg:8
    ports: ["3000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/health"]
    restart: on-failure
volumes:
  postgres: {}
