imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig', 'php'] } #assets_version: SomeVersionScheme
    default_locale:           "%locale%"
    trusted_proxies:          ~
    session:
        name:                 BAPID
        handler_id:           %session_handler%
        save_path:            %kernel.root_dir%/cache/sessions
        gc_maxlifetime:       3600
    fragments:
        enabled:              true
        path:                 /_fragment # used for controller action in template
    serializer:
        enabled:              true

# Twig Configuration
twig:
    debug:                    "%kernel.debug%"
    strict_variables:         "%kernel.debug%"
    exception_controller:     "FOS\RestBundle\Controller\ExceptionController::showAction"
    globals:
        bap:
            layout:           ::base.html.twig  # default layout across all Oro bundles
            start_route:      oro_default
        ws:
            port:             "%websocket_port%"
            host:             "%websocket_host%"

# Assetic Configuration
assetic:
    debug:                    false
    use_controller:           false
    filters:
        cssrewrite: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
        cssmin:
            file: %kernel.root_dir%/Resources/php/cssmin-v3.0.1.php

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver:       pdo_mysql
                host:         "%database_host%"
                port:         "%database_port%"
                dbname:       "%database_name%"
                user:         "%database_user%"
                password:     "%database_password%"
                charset:      UTF8
            report_source:
                driver:       pdo_mysql
                host:         "%database_host%"
                port:         "%database_port%"
                dbname:       "%database_name%"
                user:         "%database_user%"
                password:     "%database_password%"
                charset:      UTF8
            report_target:
                driver:       pdo_mysql
                host:         "%database_host%"
                port:         "%database_port%"
                dbname:       "%database_name%"
                user:         "%database_user%"
                password:     "%database_password%"
                charset:      UTF8
        types:
            date:     Oro\Bundle\LocaleBundle\DoctrineExtensions\DBAL\Types\UTCDateType
            datetime: Oro\Bundle\LocaleBundle\DoctrineExtensions\DBAL\Types\UTCDateTimeType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping:         true
        class_metadata_factory_name: Oro\Bundle\EntityExtendBundle\Mapping\ExtendClassMetadataFactory
        resolve_target_entities:
            Symfony\Component\Security\Core\User\UserInterface: Oro\Bundle\UserBundle\Entity\User


# Swiftmailer Configuration
swiftmailer:
    transport:                "%mailer_transport%"
    host:                     "%mailer_host%"
    port:                     "%mailer_port%"
    encryption:               "%mailer_encryption%"
    username:                 "%mailer_user%"
    password:                 "%mailer_password%"
    spool:                    { type: memory }

knp_paginator:
    page_range:               5         # default page range used in pagination control
    default_options:
        page_name:            page      # page query parameter name
        sort_field_name:      sort      # sort field query parameter name
        sort_direction_name:  direction # sort direction query parameter name
        distinct:             false     # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination:           OroUIBundle::pager.html.twig

fos_rest:
    view:
        failed_validation: HTTP_BAD_REQUEST
        default_engine: php
        formats:
            json: true
            xml: true
    format_listener:
        prefer_extension: true
    body_listener:
        decoders:
            json: fos_rest.decoder.json
            xml: fos_rest.decoder.xml
    routing_loader:
        default_format: json

fos_js_routing:
    routes_to_expose:         [oro_*]

be_simple_soap:
    cache:
        type:                 disk
        lifetime:             86400
        limit:                5
    services:
        soap:
            namespace:        http://symfony.loc/Api/1.0/
            binding:          rpc-literal
            resource:         .
            resource_type:    oro_soap

stof_doctrine_extensions:
    default_locale: en
    translation_fallback: true
    orm:
        default:
            translatable:     true
            tree:             true

services:
    oro.cache.abstract:
        abstract: true
        class:                Doctrine\Common\Cache\PhpFileCache
        arguments:            [%kernel.cache_dir%]
    twig.extension.intl:
         class: Twig_Extensions_Extension_Intl
         tags:
             - { name: twig.extension }
    doctrine.dbal.default.wrapped_connection:
        factory_service:      doctrine.dbal.default_connection
        factory_method:       getWrappedConnection
        class:                PDO
    session.handler.pdo:
        class:                Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments:
            - "@doctrine.dbal.default.wrapped_connection"
            -
              db_table:       oro_session
              db_id_col:      id

escape_wsse_authentication:
    authentication_provider_class: Oro\Bundle\UserBundle\Security\WsseUserProvider
    authentication_listener_class: Oro\Bundle\UserBundle\Security\WsseAuthListener

liip_imagine:
    filter_sets:
        avatar_med:
            quality:          95
            filters:
                thumbnail:    { size: [58, 58], mode: outbound }
                strip:        ~

genemu_form:
    select2: ~
    autocomplete: ~

clank:
    web_socket_server:
        port:                 %websocket_port%                # The port the socket server will listen on
        host:                 %websocket_host%                # (optional) The host ip to bind to
    session_handler:          session.handler.pdo
    periodic:
        -
            service:          "oro_wamp.db_ping"
            time:             60000                           # the time in milliseconds between the "tick" function being called

a2lix_translation_form:
    locales:                  [en, fr]
    templating:               "OroUIBundle:Form:translatable.html.twig"

lexik_maintenance:
    authorized:
        path:                 "maintenance|.*\.js"             # "maintenance" is only for demo purposes, remove in production!
#        ips:                  ["127.0.0.1"]                   # Optional. Authorized ip addresses
    driver:
        class:                Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver
        options:
            file_path:        %kernel.root_dir%/cache/lock

#
# ORO Bundles config
#
oro_ui:
    settings:
        application_name:
            value:            "OroCRM"
        application_title:
            value:            "OroCRM"

oro_require_js:
    config:
        waitSeconds: 0
    build_path: "js/oro.min.js"
    building_timeout: 3600
    build:
        optimize: "uglify2"
        preserveLicenseComments: true

oro_help:
    defaults:
        server: http://help.orocrm.com/
        prefix: Third_Party
    vendors:
        Oro:
            prefix: ~
            alias: Platform
        OroCRM:
            prefix: ~
            alias: CRM
    routes:
        oro_default:
            uri: CRM/OroCRMDashboardBundle

oro_theme:
    active_theme: oro
