imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

        # collect all log records to buffer and write them to log file on CLI command error
        message_queue.consumer.console_error:
            type: service
            id: oro_message_queue.log.handler.console_error
            handler: main
            level: debug

twig:
    base_template_class: Oro\Bundle\UIBundle\Twig\Template

oro_assetic:
    css_debug:      ~
    css_debug_all:  false

oro_message_queue:
    client:
        traceable_producer: true

#swiftmailer:
#    delivery_address: me@example.com
