imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        detailed_logs:
            type:           service
            id:             oro_logger.monolog.detailed_logs.handler
            handler:        nested
        nested:
            type:           stream
            path:           "%kernel.logs_dir%/%kernel.environment%.log"
            level:          debug

        fingers_crossed:
            type:           fingers_crossed
            action_level:   "%oro_logger.email_notification_level%"
            handler:        deduplicated
            excluded_404s:  [^/]
        deduplicated:
            type:           deduplication
            handler:        swift
        swift:
            type:           swift_mailer
            email_prototype:
                id:         oro_logger.message_factory
                method:     createMessage
            mailer:         swiftmailer.mailer.default
            level:          "%oro_logger.email_notification_level%"
            formatter:      monolog.formatter.html
