imports:
    - { resource: config_dev.yml }
    - { resource: parameters_test.yml }
    - { resource: security_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    csrf_protection: true
    router:   { resource: "%kernel.root_dir%/config/routing_test.yml" }
    profiler:
            enabled: false

services:
    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags:
            - { name: twig.extension }

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

assetic:
    debug:                    false
    use_controller:           false

monolog:
    handlers:
        main:
            level: error

oro_assetic:
    js_debug:       ~
    js_debug_all:   false
    css_debug:      ~
    css_debug_all:  false

oro_require_js:
    js_engine: ~
