#
# 3rd party routes
#
nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_imagine:
    resource: .
    type:     imagine

#
# ORO routes
#
oro_default:
    pattern:  /
    defaults:
        template:    OroCRMDashboardBundle:Default:index.html.twig
        _controller: FrameworkBundle:Template:template

oro_auto_routing:
    resource: .
    type:     oro_auto
