orocrm_contact:
    resource: "@OroCRMContactBundle/Resources/config/routing.yml"
    prefix:   /

orocrm_account:
    resource: "@OroCRMAccountBundle/Resources/config/routing.yml"

oro_default:
    pattern:  /
    defaults:
        template:    OroCRMDashboardBundle:Default:index.html.twig
        _controller: FrameworkBundle:Template:template

oro_ui:
    resource: "@OroUIBundle/Resources/config/routing.yml"
    prefix:   /ui

oro_form:
    resource: "@OroFormBundle/Resources/config/routing.yml"
    prefix:   /

oro_user:
    resource: "@OroUserBundle/Resources/config/routing.yml"

oro_search:
    resource: "@OroSearchBundle/Resources/config/routing.yml"
    prefix:   /

oro_navigation:
    resource: "@OroNavigationBundle/Resources/config/routing.yml"
    prefix:   /

oro_windows:
    resource: "@OroWindowsBundle/Resources/config/routing.yml"
    prefix: /

oro_soap:
    resource: "@OroSoapBundle/Resources/config/routing.yml"
    prefix:   /api

oro_dataflow:
    resource: "@OroDataFlowBundle/Resources/config/routing.yml"

oro_config:
    resource: "@OroConfigBundle/Resources/config/routing.yml"

oro_dataaudit:
    resource: "@OroDataAuditBundle/Resources/config/routing.yml"

nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_imagine:
    resource: .
    type:     imagine

oro_address:
    resource: "@OroAddressBundle/Resources/config/routing.yml"
    prefix:   /

_bazinga_exposetranslation:
    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"

_apy_jsformvalidation:
    resource: "@APYJsFormValidationBundle/Resources/config/routing/routing.yml"

oro_assets:
    resource: .
    type: oro_assetic
