security:
    firewalls:
        main:
            organization-http-basic:
                realm: "Secured REST Area"
            provider: oro_user
            http-basic: false
            organization-form-login: false
            logout: false
            remember_me: false
            anonymous: true
    acl:
        connection: default
