imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.project_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }
    ide: phpstorm

web_profiler:
    toolbar: true
    excluded_ajax_paths: '^/((index(_[\w]+)|app(_[\w]+)?)\.php/)?(_wdt|bundles)'
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

oro_message_queue:
    client:
        traceable_producer: true

#swiftmailer:
#    delivery_address: me@example.com
