imports:
    - { resource: config.yml }
    - { resource: parameters_test.yml }
    - { resource: security_test.yml }

parameters:
    doctrine.dbal.connection_factory.class: 'Oro\Component\Testing\Doctrine\PersistentConnectionFactory'
    message_queue_transport: 'dbal'
    message_queue_transport_config: {}
    main_log_channels: []

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    csrf_protection: true
    profiler:
        enabled: false

monolog:
    handlers:
        fingers_crossed:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [ 404, 405 ]
            channels: [ "!event" ]
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: '%main_log_channels%'

swiftmailer:
    logging: true
    disable_delivery: true

# configure loose default password requirements for auto-generated test users
oro_user:
    settings:
        password_min_length:
            value: 2
        password_lower_case:
            value: false
        password_upper_case:
            value: false
        password_numbers:
            value: false
        password_special_chars:
            value: false

twig:
    strict_variables: true
    debug: false

oro_api:
    settings:
        web_api:
            value: true
